[project]
name = "lang-graph-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask",
    "langchain",
    "langchain-openai",
    "langchain-core",
    "langgraph"
]
